name: smart_dzala
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  firebase_auth: ^4.4.0
  firebase_database: ^10.1.0
  fl_chart: ^0.61.0

  flutter:
    sdk: flutter
  geolocator: ^9.0.2
  syncfusion_flutter_charts: ^21.1.41
  google_maps_flutter: ^2.2.5
  charts_flutter: ^0.12.0
  percent_indicator: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
